name: Playwright Tests and PR Check

on:
  push:
    branches: [master]

jobs:
  create-pr-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # Step to check if a PR already exists and create one if not
      - name: Create or use existing PR
        id: create_pr
        run: |
          PR_EXISTS=$(gh pr list --state open --head "$(git rev-parse --abbrev-ref HEAD)" --json number --jq '.[0].number' || echo "")
          if [ -z "$PR_EXISTS" ]; then
            gh pr create --title "Automated PR for e2e tests" --body "This PR was created automatically to run e2e tests."
          else
            echo "PR already exists: #$PR_EXISTS"
            echo "PR_NUMBER=$PR_EXISTS" >> $GITHUB_ENV
          fi

      - name: Install Playwright and dependencies
        run: |
          npx playwright install
          npm i playwright install --with-deps

      - name: Run Playwright tests
        id: run_tests
        run: |
          npx playwright test | tee output.log
          if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
            echo "Playwright tests failed due to a snapshot issue."
            echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
            exit 1
          elif grep -q "failed" output.log; then
            echo "Playwright tests failed due to a non-snapshot issue."
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Comment on PR based on the test result
      - name: Comment on PR with report link if differences found
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ### Playwright visual snapshot differences detected.
            View the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }}) to review the visual differences.
            **To approve the snapshot changes and update the snapshots, please comment:** /approve-snapshots

      # Close PR if tests pass
      - name: Close PR if tests pass
        if: ${{ success() }}
        run: |
          gh pr close $(gh pr list --state open --json number --jq '.[0].number')

      # Send Slack notification if differences found
      - name: Send Slack notification if differences found
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Playwright snapshot differences detected. View the report here: ${{ steps.artifact-upload.outputs.artifact-url }}"
          }' $SLACK_WEBHOOK_URL
