name: Playwright Tests and PR Check

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test-and-update-pr-on-failure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright and dependencies
        run: |
          npx playwright install
          npm install --with-deps

      - name: Run Playwright tests
        id: run_tests
        run: |
          npx playwright test | tee output.log
          if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
            echo "Playwright tests failed due to a snapshot issue."
            echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
            exit 1
          elif grep -q "failed" output.log; then
            echo "Playwright tests failed due to a non-snapshot issue."
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Fetch master snapshots
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        run: |
          # Define the directory for snapshots from the master branch
          MASTER_SNAPSHOTS_DIR="tests/old-snapshots"
          mkdir -p $MASTER_SNAPSHOTS_DIR
          
          # Fetch the latest commit from master
          git fetch origin master
          
          # Checkout the master branch in a temporary directory
          git worktree add /tmp/master-snapshots origin/master
          
          # Copy the snapshots from master
          cp -r /tmp/master-snapshots/playwright-report/* $MASTER_SNAPSHOTS_DIR/
          
          # Remove the temporary worktree
          git worktree remove /tmp/master-snapshots
          
          echo "Snapshots from master branch copied to $MASTER_SNAPSHOTS_DIR."

      - name: Create or update branch and PR if snapshot differences found
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          # Define the branch name
          BRANCH_NAME="snapshot-update"

          # Fetch all branches to ensure we have access to the remote branch
          git fetch origin

          # Save necessary files
          mkdir -p /tmp/save-files
          cp -r playwright-report /tmp/save-files/
          find tests -name '*-snapshots' -type d -exec cp -r {} /tmp/save-files/ \;
          cp output.log /tmp/save-files/
          git clean -fd

          # Check if the branch already exists remotely
          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
            echo "Branch $BRANCH_NAME exists remotely. Checking out and pulling latest changes."
            git checkout -b $BRANCH_NAME origin/$BRANCH_NAME
            git pull origin $BRANCH_NAME
          else
            echo "Branch $BRANCH_NAME does not exist remotely. Creating new branch."
            git checkout -b $BRANCH_NAME
          fi

          # Restore saved files
          cp -r /tmp/save-files/* .

          # Check for changes and push if detected
          if [[ -n $(git status -s) ]]; then
            echo "Changes detected. Committing and pushing."
            git add .
            git commit -m "Automated snapshot update"
            git push origin $BRANCH_NAME

            # Check if a PR exists for this branch
            EXISTING_PR=$(gh pr list --head $BRANCH_NAME --state open --limit 1)

            if [ -z "$EXISTING_PR" ]; then
              # Create a new PR if none exists
              echo "Creating new PR for branch $BRANCH_NAME"
              gh pr create --title "Automated PR for Playwright snapshot updates" \
                           --body "Snapshot differences detected. Please review the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }})." \
                           --head $BRANCH_NAME --base master
            else
              echo "PR already exists for branch $BRANCH_NAME. Adding comment."
              PR_NUMBER=$(echo "$EXISTING_PR" | grep -oP '#\K\d+')
              gh pr comment "$PR_NUMBER" --body "Snapshot differences detected. Please review the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }})."
            fi
          else
            echo "No changes detected. Skipping commit and PR creation."
          fi

      - name: Compare snapshots and add diff to PR comment
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        run: |
          # Install ImageMagick for image diff
          sudo apt-get install -y imagemagick
          
          # Define directories for snapshots
          NEW_SNAPSHOTS_DIR="playwright-report"
          DIFF_DIR="tests/diffs"
          mkdir -p $DIFF_DIR

          # Loop through all newly generated images
          for new_image in $NEW_SNAPSHOTS_DIR/*.png; do
            echo "Checking image: $new_image"
          
            # Find the corresponding master image by the same name
            master_image="$MASTER_SNAPSHOTS_DIR/$(basename $new_image)"
          
            if [[ -f "$master_image" ]]; then
              # Perform the diff
              diff_image="$DIFF_DIR/diff_$(basename $new_image)"
              compare -metric AE "$master_image" "$new_image" "$diff_image" 2>&1 | tee -a diff.log
              if [[ $? -ne 0 ]]; then
                echo "Image difference found: $diff_image"
              else
                echo "No difference found between $new_image and $master_image."
              fi
            else
              echo "No corresponding image found on master for: $new_image"
            fi
          done

      - name: Upload diff images as an artifact
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-diffs
          path: tests/diffs
          retention-days: 30

      - name: Add diff images link in PR comment
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        run: |
          if [ -d "tests/diffs" ] && [ "$(ls -A tests/diffs)" ]; then
            echo "Differences found. Adding diff images link in PR comment."
            DIFF_ARTIFACT_URL="${{ steps.artifact-upload.outputs.artifact-url }}"
            EXISTING_PR=$(gh pr list --head $BRANCH_NAME --state open --limit 1)
            PR_NUMBER=$(echo "$EXISTING_PR" | grep -oP '#\K\d+')
          
            gh pr comment "$PR_NUMBER" --body "### Snapshot difference detected between:
            - [Diff images]($DIFF_ARTIFACT_URL)"
          else
            echo "No differences found. Skipping PR comment."
          fi
