name: Playwright Tests and PR Check

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test-and-update-pr-on-failure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright and dependencies
        run: |
          npx playwright install
          npm install --with-deps

      - name: Run Playwright tests
        id: run_tests
        run: |
          npx playwright test | tee output.log
          if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
            echo "Playwright tests failed due to a snapshot issue."
            echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
            exit 1
          elif grep -q "failed" output.log; then
            echo "Playwright tests failed due to a non-snapshot issue."
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Create or update branch and PR if snapshot differences found
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          # Define the branch name
          BRANCH_NAME="snapshot-update"

          # Fetch all branches to ensure we have access to the remote branch
          git fetch origin

          # Clean untracked files but save the ones we need
          mkdir -p /tmp/save-files
          cp -r playwright-report /tmp/save-files/
          
          # Generic approach to save all snapshot directories
          find tests -name '*-snapshots' -type d -exec cp -r {} /tmp/save-files/ \;
          
          cp output.log /tmp/save-files/
          git clean -fd

          # Check if the branch already exists remotely
          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
            echo "Branch $BRANCH_NAME exists remotely. Checking out and pulling latest changes."
            git checkout -b $BRANCH_NAME origin/$BRANCH_NAME
            git pull origin $BRANCH_NAME
          else
            echo "Branch $BRANCH_NAME does not exist remotely. Creating new branch."
            git checkout -b $BRANCH_NAME
          fi

          # Restore saved files
          cp -r /tmp/save-files/* .

          # Check if there are any changes
          if [[ -n $(git status -s) ]]; then
            echo "Changes detected. Committing and pushing."
            # Stage all changes and commit
            git add .
            git commit -m "Automated snapshot update"

            # Push the branch to the repository
            git push origin $BRANCH_NAME

            # Check if a PR exists for this branch
            PR_NUMBER=$(gh pr list --head $BRANCH_NAME --state open --json number --jq '.[0].number')

            if [ -z "$PR_NUMBER" ]; then
              # Create a new PR if none exists
              echo "Creating new PR for branch $BRANCH_NAME"
              PR_NUMBER=$(gh pr create --title "Automated PR for Playwright snapshot updates" --body "Snapshot differences detected. Please review the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }})." --head $BRANCH_NAME --base master --json number --jq '.number')
            else
              echo "PR already exists: #$PR_NUMBER - updated with latest changes"
            fi

            # Add comment to the PR
            if [ -n "$PR_NUMBER" ]; then
              gh pr comment $PR_NUMBER --body "### Playwright visual snapshot differences detected.
          View the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }}) to review the visual differences."
            else
              echo "Failed to create or find PR. Unable to add comment."
            fi
          else
            echo "No changes detected. Skipping commit and PR creation."
          fi

      # Commented out Slack notification step
      # - name: Send Slack notification if differences found
      #   if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   run: |
      #     curl -X POST -H 'Content-type: application/json' --data '{
      #       "text": "Playwright snapshot differences detected. View the report here: ${{ steps.artifact-upload.outputs.artifact-url }}"
      #     }' $SLACK_WEBHOOK_URL

      # New step to compare snapshots and add diff to PR comment
      - name: Compare snapshots and add diff to PR comment
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        run: |
          # Install ImageMagick for image diff
          sudo apt-get install -y imagemagick

          # Define directories for snapshots (assuming 'tests' contains the snapshots)
          OLD_SNAPSHOTS_DIR="tests/old-snapshots"
          NEW_SNAPSHOTS_DIR="tests/new-snapshots"
          DIFF_DIR="tests/diffs"
          mkdir -p $DIFF_DIR

          # Compare snapshots using ImageMagick's compare tool
          for old_image in $OLD_SNAPSHOTS_DIR/*.png; do
            new_image="$NEW_SNAPSHOTS_DIR/$(basename $old_image)"
            if [[ -f "$new_image" ]]; then
              # Check if the corresponding image exists in the master branch
              git fetch origin master
              master_image_path="tests/old-snapshots/$(basename $old_image)"
              if git ls-tree -r origin/master --name-only | grep -q "$master_image_path"; then
                # If the image exists in master, do the diff
                diff_image="$DIFF_DIR/diff_$(basename $old_image)"
                compare -metric AE "$old_image" "$new_image" "$diff_image" 2>&1 | tee -a diff.log
                if [[ $? -ne 0 ]]; then
                  echo "Image difference found: $diff_image"
                  # Upload the diff image as an artifact
                  mv "$diff_image" "$DIFF_DIR/"
                fi
              else
                echo "No corresponding image found in master for $old_image. Skipping diff."
              fi
            fi
          done

      # Correct placement of Upload diff images as an artifact step
      - name: Upload diff images as an artifact
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-diffs
          path: $DIFF_DIR
          retention-days: 30

      # Add diff link in PR comment if diffs were found
      - name: Add diff images link in PR comment
        if: ${{ failure() && env.SNAPSHOT_DIFFERENCES == 'true' }}
        run: |
          if [[ -n "$(ls -A $DIFF_DIR)" ]]; then
            DIFF_ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/artifacts/$(echo $upload_artifact | jq -r .id)"
            gh pr comment $PR_NUMBER --body "### Snapshot difference detected between:
            - [Old snapshot](https://github.com/${{ github.repository }}/blob/master/$master_image_path)
            - [New snapshot](https://github.com/${{ github.repository }}/blob/${BRANCH_NAME}/$new_image)
            - [Diff images](https://github.com/${{ github.repository }}/actions/artifacts/${DIFF_ARTIFACT_URL})"
          else
            echo "No differences found. No diff images uploaded."
          fi
